### PR TITLE
Added models for org struct

### PR DESCRIPTION
**Pull request by hclauron**
I added demographics, camp page, org leader, and camp officer models. Also, please check the added code in the serializer, views, and url. The model for camp page model still needs modification. I'm up for suggestions. No testing for this yet.

### CODE REVIEW

**Review by temata — COMMENTED** [review]
Thanks for adding in some of the models, serializers, and views for this sprint! 

I made a little revision ra on the urls.py. The url names were made plural since a list of that content (e.g. orgleader) is returned when accessing that url. That is all, this PR is good and consistent.

Although it has come to our notice that extra models will be needed, given a complex org structure. We'll just add them to this PR.

**Comment by hclauron** [comment]
Models for the leaders has been modified to match with the organization structure. Please advise me for better implementation. Thanks!

**Comment by temata** [comment]
Hello! Reviewed your newly added commits, and I see that you had made good use with the Enums. I just added in a few adjustments by nesting them within the models that they will solely be used. It maximizes your applications of enums, while increasing code readability. I also pitched in a suggestion with the _str_ naming and are commented within models.py.

Do check this commit at [dbb900f](https://github.com/ManaTech-Group-4/KaLunWA/pull/33/commits/dbb900f4ef5e6f21eb277b794abd2af0a1d3f6dc) to see the changes, and tell me what you think. If all goes well, you can go and merge this with main. Thanks!

**Comment by hclauron** [comment]
> Hello! Reviewed your newly added commits, and I see that you had made good use with the Enums. I just added in a few adjustments by nesting them within the models that they will solely be used. It maximizes your applications of enums, while increasing code readability. I also pitched in a suggestion with the _str_ naming and are commented within models.py.
> 
> Do check this commit at [dbb900f](https://github.com/ManaTech-Group-4/KaLunWA/pull/33/commits/dbb900f4ef5e6f21eb277b794abd2af0a1d3f6dc) to see the changes, and tell me what you think. If all goes well, you can go and merge this with main. Thanks!

Looks much better. It's more readable this way. Thanks!

**Pull request merged**
